### ISSUE TITLE
Couple comments from Blackfriday

### ISSUE THREAD

**Issue by rtfb** [Depado/bfchroma#1]
Hi Depado. Thanks for building this package!

A couple comments from me:

1. Can you provide a constructor that picks some sane defaults for the fallback renderer and the color scheme? It would be super neat if using Blackfriday+bfchrome were as easy as this:

    ```go
    html := bf.Run([]byte(md), bf.WithRenderer(bfchroma.NewRenderer()))
    ```

    There are several options for providing both easy defaults and customization: you can have several 
    constructors, an `Options` struct or the [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) approach. Pick any of them 
    and make bfchroma extensible.

2. In addition to that, please export the `renderWithChroma` function for people who might want to use your basic functionality, but incorporate it into a larger renderer of their own.

**Comment by Depado** [comment]
Sure thing ! I'm on it :smile:

**Comment by Depado** [comment]
Done 😄 
I simply have an issue with the `html.WithClasses()` option of Chroma since it expects the CSS classes to be written separately ([more info here](https://github.com/alecthomas/chroma#the-html-formatter))

Otherwise this package now allows :
- Extending a Blackfriday Renderer by passing it in the `Extend(bf.Renderer)` option
- Disabling language auto-detection using the `WithoutAutodetect()` option
- Passing options to Chroma's HTML renderer using `ChromaOptions(...html.Option)` option
- Modifying the style used by chroma using the `Style(style)` option

**Comment by rtfb** [comment]
Super neat! Thank you!! :-)

Make sure to add a link to your docs to the README: https://godoc.org/github.com/Depado/bfchroma (and probably add some package-level preamble).

/me heads off to add a link to this from the Blackfriday list of other renderers...

**Comment by Depado** [comment]
will do and once this is done I'll close that ! Thanks for all your help :D

**Comment by Depado** [comment]
Done ☺
